### ISSUE TITLE
USER STORY: Comments feature

### ISSUE THREAD

**Issue by DaveCaulfield** [DaveCaulfield/everything-but-the-gluten#15]
As a **Site Member** I can **write comments on recipes** so that **I can interact with the community**

**Acceptance Criteria**:
-  1: user can write a comment.
- 2: comment is submitted for approval

#Tasks
- [x] Task 1: create comment model
- [x] Task 2: create view
- [x] Task 3: create comment form
- [x] Task 4: update recipe detail template
