### ISSUE TITLE
USER STORY: <TITLE>

### ISSUE THREAD

**Issue by DaveCaulfield** [DaveCaulfield/everything-but-the-gluten#16]
As a **site member** I can **see my published recipes** so that **I can easily find my own recipes**

**Acceptance Criteria**:
-  1: User can click a link to see their published recipes

**Tasks**
- [] Task 1: create view
- [] Task 2: create url
- [] Task 3: update navbar with link
