### ISSUE TITLE
USER STORY: Users Favourite recipes

### ISSUE THREAD

**Issue by DaveCaulfield** [DaveCaulfield/everything-but-the-gluten#18]
As a **site member** I can **see my Favourite recipes** so that **I can easily access my favourite recipes**

**Acceptance Criteria**:
-  1: User can click a link to see their favourite recipes

**Tasks**
- [x] Task 1: create view
- [x] Task 2: create template
- [x] Task 3: update navbar with link
- [x]  Task 4: create URL
