### ISSUE TITLE
USER STORY: View recipe details

### ISSUE THREAD

**Issue by DaveCaulfield** [DaveCaulfield/everything-but-the-gluten#3]
As a **site visitor** I can **click on a recipe** so that **I can see all the ingredients and instructions**

**Acceptance Criteria**:
-  1: user can click on a link to display full recipe details.

#Tasks
- [x] Task 1: create view
- [x] Task 2: create template
- [x] Task 3: create url
- [x] Task 4: add link
